 # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278b6cab5ac60ab79490382965b5d4496290489733e579cb2f0c4066771715e0b4aa8b17cdc2b4f2ea56dd154650f25b9bc557387a043f4f91799a950f82285d
  mail_id: "shivasorab@gmail.com"
  password: "hiremath@123"
  authentication: "plain"
  address: "smtp.gmail.com"
  port: "587"
  domain: "localhost:3000"
  enable_starttls_auto: "true"
  facebook_appid: "2267844863527308"
  github_appid: "2735ebc456b12c8e45ad"
  google_appid: "552943472988-c3ml106qmbpjduv0vqe1pvett52hkskj.apps.googleusercontent.com"
  facebook_secret_key: "fe7c8abba12ee9eb8c7664fbb029e7f1"
  github_secret_key: "bc2313befedf3d309f6785427c9ea828660fbc5b"
  google_secret_key: "PQHIqgBEuo0LvcVWexIzO5oK"
  facebook_callback: "http://localhost:3001/users/auth/facebook/callback"
  google_callback: "https://localhost:3001/users/auth/google_auth2/callback"
  github_callback: "http://localhost:3001/users/auth/github/callback"

test:
  secret_key_base: 2ac7b9937937eff50763b66f1de4b682eda50d65f09beed0703c6a67ac1ca00a62d95e7ce3c40370bcee69552b9146b87a52411484ae48d2eab4d222c54f126b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail_id: "shivasorab@gmail.com"
  password: "hiremath@123"
  authentication: "plain"
  address: "smtp.gmail.com"
  port: "587"
  domain: "localhost:3000"
  enable_starttls_auto: "true"
  facebook_appid: "2267844863527308"
  github_appid: "2735ebc456b12c8e45ad"
  google_appid: "552943472988-c3ml106qmbpjduv0vqe1pvett52hkskj.apps.googleusercontent.com"
  facebook_secret_key: "fe7c8abba12ee9eb8c7664fbb029e7f1"
  github_secret_key: "bc2313befedf3d309f6785427c9ea828660fbc5b"
  google_secret_key: "PQHIqgBEuo0LvcVWexIzO5oK"
  facebook_callback: https://estateagency-in.herokuapp.com/users/auth/facebook/callback"
  google_callback: "https://estateagency-in.herokuapp.com/users/auth/google_auth2/callback"
  github_callback: https://estateagency-in.herokuapp.com/users/auth/github/callback"


  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.