# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278b6cab5ac60ab79490382965b5d4496290489733e579cb2f0c4066771715e0b4aa8b17cdc2b4f2ea56dd154650f25b9bc557387a043f4f91799a950f82285d
  paytm_credentials:
  PASSWORD : "hiremath@123"
  GMAIL : 'shivasorab@gmail.com'
  staging:
    mid: "LGg8ngBM4jLL!z2M"
    merchant_key: "VIoyzj52535886084363"
    industry_type_id: "Retail"
    txn_status_url: "https://pguat.paytm.com/oltp/HANDLER_INTERNAL/getTxnStatus"
    app:
      website: "APP_STAGING"
      channel_id: "WAP"
    web:
      website: "WEB_STAGING"
      channel_id: "WEB"
      payment_url: "https://pguat.paytm.com/oltp-web/processTransaction"
      callback_url: "http://localhost:3001/paytm_response"
  production:
    mid: ""
    merchant_key: ""
    industry_type_id: "Retail109"
    txn_status_url: "https://secure.paytm.in/oltp/HANDLER_INTERNAL/getTxnStatus"
    app:
      website: ""
      channel_id: "WAP"
    web:
      website: ""
      channel_id: "WEB"
      payment_url: "https://secure.paytm.in/oltp-web/processTransaction"
      callback_url: "http://localhost:3000/order-processed"
test:
  secret_key_base: 2ac7b9937937eff50763b66f1de4b682eda50d65f09beed0703c6a67ac1ca00a62d95e7ce3c40370bcee69552b9146b87a52411484ae48d2eab4d222c54f126b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.